services:
  - type: web
    name: utr-checker
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: utr-checker-db
          property: connectionString
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
databases:
  - name: utr-checker-db
